version: '3'
services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
